apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: "Babbage"
  name: "babbage"
  description: "Legacy part of the ONS website"
  annotations:
    github.com/project-slug: backstage-dummy-org/babbage
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: "digital-publishing"
