version: '2'
services:
  elastic:
    image: elastic
    ports:
    - "9200:9200"
    - "9300:9300"
  maven:
    image: maven
    depends_on :
     - elastic
    command:
    - "ls -lart"
    - babbage/ci/compose/compose-integration-tests.sh
    volumes:
    - babbage:babbage:rw
