---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-git

inputs:
  - name: build
  - name: artifacts
  - name: babbage

outputs:
  - name: deployment

run:
  path: babbage/ci/scripts/deployment-bundle.sh
