---


resource_types:
  - name: s3-simple
    type: docker-image
    source:
      repository: lloydg/s3-resource-simple

resources:
  - name: feature-load-document-concourse
    type: git
    source:
      uri: https://github.com/ONSdigital/babbage.git
      branch: feature/load-document-content-concourse

  - name: feature-load-document-concourse-integration-cucumber
    type: s3-simple
    source:
      bucket: dp-build-feature-test-report
      path: feature-tests
      target: feature-tests

jobs:
  - name: feature-load-document-concourse-unit
    public: true
    plan:
      - aggregate :
        - get: babbage
          trigger: true
          resource: feature-load-document-concourse
      - task: unit
        file: babbage/ci/unit.yml
      - put: feature-load-document-concourse-integration-cucumber
