---
resources:
  - name: feature-load-document-concourse
    type: git
    source:
      uri: https://github.com/ONSdigital/babbage.git
      branch: feature/load-document-content-concourse

  - name: mavenastic
    type: docker-image
    source:
      repository: guidof/mavenastic


  - name: feature-load-document-concourse-integration-cucumber
    type: s3
    source:
#      access_key_id: <%= ENV.fetch('AWS_ACCESS_KEY_ID') %>
#      secret_access_key: <%= ENV.fetch('AWS_ACCESS_KEY') %>
    bucket: dp-build-feature-test-report
    regexp: feature-load-document-concourse\/.*\.tar\.gz
    region_name: eu-west-1
    private: true


jobs:
  - name: feature-load-document-concourse-unit
    public: true
    plan:
      - aggregate :
        - get: babbage
          trigger: true
          resource: feature-load-document-concourse
        - get: mavenastic
          params:
             save: true
      - task: unit
        file: babbage/ci/unit.yml

  - name: feature-load-document-concourse-build
    public: true
    plan:
      - get: babbage
        passed: [feature-load-document-concourse-unit]
        trigger: true
        resource: feature-load-document-concourse
      - task: npm-install
        file: babbage/ci/npm-install.yml
      - task: compile
        file: babbage/ci/compile.yml
      - task: revision
        file: babbage/ci/revision.yml
      - task: bundle
        file: babbage/ci/build-bundle.yml

