---
resources:
  - name: feature-load-document-concourse
    type: git
    source:
      uri: https://github.com/ONSdigital/babbage.git
      branch: feature/load-document-content-concourse
  - name: elastic
    type: docker-image
    source:
      repository: guidof/onswebsite-search
  - name: mavenastic
    type: docker-image
    source:
      repository: guidof/mavenastic:0.0.1
  - name: maven
    type: docker-image
    source:
      repository: maven
  - name: integration-container
    type: docker-image
    source:
      repository: amidos/dcind
#  - name: feature-load-document-concourse-integration-cucumber
#    type: s3
#    source:
##      access_key_id: <%= ENV.fetch('AWS_ACCESS_KEY_ID') %>
##      secret_access_key: <%= ENV.fetch('AWS_ACCESS_KEY') %>
##      bucket: ons-web-cucumber
#       bucket: ons-web-temp
##      regexp: <%= ENV.fetch('PIPELINE_NAME') %>/.*-?(\d+\.\d+\.\d+)(?:-rc\d+)?.tar.gz
#       region_name: eu-west-1
#       private: true



# - name: feature-load-document-concourse-build-bundle
# - name: feature-load-document-concourse-image

jobs:
  - name: feature-load-document-concourse-unit
    public: true
    plan:
      - aggregate :
        - get: babbage
          trigger: true
          resource: feature-load-document-concourse
        - get: mavenastic
          params:
             save: true
      - task: unit
        file: babbage/ci/unit.yml
#
#  - name: feature-load-document-concourse-build
#    public: true
#    plan:
#      - get: babbage
#        passed: [feature-load-document-concourse-unit]
#        trigger: true
#        resource: feature-load-document-concourse
#      - task: npm-install
#        file: babbage/ci/npm-install.yml
#      - task: compile
#        file: babbage/ci/compile.yml
#      - task: revision
#        file: babbage/ci/revision.yml
#      - task: bundle
#        file: babbage/ci/build-bundle.yml
#

  - name: feature-load-document-concourse-integration
    public: true
    plan:
    - aggregate :
      - get: babbage
        passed: [feature-load-document-concourse-unit]
        trigger: true
        resource: feature-load-document-concourse
      - get: elastic
        params:
          save: true
      - get: maven
        params:
          save: true
      - get: integration-container
        params:
          save: true
    - task: integration-test
      privileged: true
      file: babbage/ci/integration-test.yml
#    - put: feature-load-document-concourse-integration-cucumber
#      params:
#        acl: private
#        file: integration-tests/*tar.gz

    # - put: feature-load-document-concourse-build-bundle
    #   params:
    #     acl: private
    #     file: build/*.tar.gz


  # - name: feature-load-document-concourse-image
  #   plan:
  #   - get: build-bundle
  #     passed: [feature-load-document-concourse-build]
  #     resource: feature-load-document-concourse-build-bundle
  #   - get: babbage
  #     passed: [feature-load-document-concourse-build]
  #     trigger: true
  #     resource: feature-load-document-concourse
  #   - task: unpack
  #     file: babbage/ci/unpack.yml
  #   - put: feature-load-document-concourse-image
  #     params:
  #       build: .
  #       dockerfile: babbage/Dockerfile
  #       tag: build/revision
  #       tag_prefix: concourse-
