---


resource_types:
   # Lloyds custom S3 simple deployment
  - name: s3-simple
    type: docker-image
    source:
      repository: lloydg/s3-resource-simple

resources:
  - name: feature-load-content-documents-featureTest
    type: git
    source:
      uri: https://github.com/ONSdigital/babbage.git
      branch: feature/load-content-documents-featureTest

  # Outbound Job to send FeatureTest results to S3
  - name: feature-load-content-documents-featureTest-integration-cucumber
    type: s3-simple
    source:
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_access_key}}
      bucket: dp-build-feature-test-report
      path: load-document-content-concourse
      target: reports

jobs:
  - name: feature-load-content-documents-featureTest-unit
    public: true
    plan:
      - get: babbage
        trigger: true
        resource: feature-load-content-documents-featureTest
      - task: unit
        file: babbage/ci/unit.yml
      - put: feature-load-content-documents-featureTest-integration-cucumber
